"""change credit card number to bigint

Revision ID: 25475dc79e10
Revises: 0f12cef341bc
Create Date: 2022-04-12 18:21:40.001492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25475dc79e10'
down_revision = '0f12cef341bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_cards', 'cardNumber',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_cards', 'cardNumber',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
