"""fix mortgage accountType

Revision ID: 29c172610f92
Revises: 25475dc79e10
Create Date: 2022-04-12 18:33:37.045326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c172610f92'
down_revision = '25475dc79e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mortgages', 'accountType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mortgages', sa.Column('accountType', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
