"""added creditcard limits

Revision ID: e112ddfa4d58
Revises: e6c7852bb214
Create Date: 2022-04-15 11:25:28.075711

"""
from alembic import op
import sqlalchemy as sa
import bmuapi

# revision identifiers, used by Alembic.
revision = 'e112ddfa4d58'
down_revision = 'e6c7852bb214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column(
        'creditLimit', bmuapi.database.tables.NumericMoney(), nullable=True))
    op.add_column('credit_cards', sa.Column(
        'moneyLimit', bmuapi.database.tables.NumericMoney(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_cards', 'moneyLimit')
    op.drop_column('credit_cards', 'creditLimit')
    # ### end Alembic commands ###
