"""new money type

Revision ID: e6c7852bb214
Revises: 29c172610f92
Create Date: 2022-04-15 11:07:36.675169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c7852bb214'
down_revision = '29c172610f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ssn', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ssn')
    # ### end Alembic commands ###
