"""initial changes

Revision ID: f29d6433a6af
Revises: 
Create Date: 2022-04-07 19:45:57.129936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f29d6433a6af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checking_savings', 'accountName',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('mortgages', 'accountName',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.execute('ALTER TABLE mortgages ALTER COLUMN "paymentDueDate" TYPE timestamp with time zone USING to_timestamp("paymentDueDate");')
    op.execute('ALTER TABLE mortgages ALTER COLUMN "startDate" TYPE timestamp with time zone USING to_timestamp("startDate");')
    op.add_column('transaction_history', sa.Column(
        'accountID', sa.Integer(), nullable=True))
    op.execute('ALTER TABLE transaction_history ALTER COLUMN "transactionDate" TYPE timestamp with time zone USING to_timestamp("transactionDate");')
    op.create_foreign_key(None, 'transaction_history',
                          'user_accounts', ['accountID'], ['id'])
    op.drop_constraint('user_accounts_historyID_fkey',
                       'user_accounts', type_='foreignkey')
    op.drop_column('user_accounts', 'historyID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column(
        'historyID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_accounts_historyID_fkey',
                          'user_accounts', 'transaction_history', ['historyID'], ['id'])
    op.drop_constraint(None, 'transaction_history', type_='foreignkey')
    op.alter_column('transaction_history', 'transactionDate',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.drop_column('transaction_history', 'accountID')
    op.alter_column('mortgages', 'startDate',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('mortgages', 'paymentDueDate',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('mortgages', 'accountName',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('checking_savings', 'accountName',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    # ### end Alembic commands ###
