"""nextPayment for CreditCard and Mortgage

Revision ID: fa85f28934dc
Revises: e112ddfa4d58
Create Date: 2022-04-18 18:11:54.381756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa85f28934dc'
down_revision = 'e112ddfa4d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('nextPayment', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('mortgages', sa.Column('nextPayment', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mortgages', 'nextPayment')
    op.drop_column('credit_cards', 'nextPayment')
    # ### end Alembic commands ###
