FROM node:latest
LABEL maintainer="deh0022@uah.edu"
LABEL version="0.1"
LABEL description="frontend development build for BMU"

WORKDIR /app
COPY package*.json ./
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL $REACT_APP_API_URL

RUN npm install
EXPOSE 3000
CMD ["npm","start"]