version: '3.9'

services:
  bmu-database:
    restart: always
    build:
      context: "./database"
      dockerfile: "./Dockerfile"
    ports: 
      - "5432:5432"
  bmu-api:
    restart: always
    build:
      context: "./api"
      dockerfile: "./Dockerfile"
  bmu-frontend:
    restart: always
    build:
      args:
        - REACT_APP_API_URL="test"
      context: "./frontend"
      dockerfile: "./Dockerfile"
  bmu-main:
    restart: always
    build:
      context: "./nginx"
      dockerfile: "./Dockerfile"
    ports: 
      - "80:80"
