version: '3.9'

services:
  bmu-database:
    restart: always
    build:
      context: "./database"
      dockerfile: "./Dockerfile"
    ports: 
      - "5432:5432"
  bmu-frontend:
    restart: always
    build:
      context: "./frontend"
      dockerfile: "./Dockerfile"
    ports: 
      - "8008:3000"