version: '3.9'

services:
  bmu-database-dev:
    restart: always
    build:
      context: "./database"
      dockerfile: "./Dockerfile"
    networks:
      - dev-network
    ports: 
      - "5432:5432"
  bmu-api-dev:
    restart: always
    build:
      context: "./api"
      dockerfile: "./Dockerfile"
    networks:
      - dev-network
  bmu-frontend-dev:
    restart: always
    build:
      context: "./frontend"
      dockerfile: "./DockerfileDev"
    networks:
      - dev-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
  bmu-main-dev:
    restart: always
    build:
      context: "./nginx"
      dockerfile: "./DockerfileDev"
    networks:
      - dev-network
    ports: 
      - "80:80"

networks:
  dev-network:
    name: bmu-dev-network