version: '3.9'

services:
  bmu-database:
    restart: always
    build:
      context: "./database"
      dockerfile: "./Dockerfile"
    ports:
      - "5432:5432"
  bmu-api:
    restart: always
    build:
      context: "./api"
      dockerfile: "./Dockerfile"
    environment:
      - ROUTING_NUMBER=456546102
      - CHECKING_DIVIDEND_RATE=0.03
      - SAVINGS_DIVIDEND_RATE=0.06
      - CC_INTEREST_RATE=20
      - MORTGAGE_INTEREST_RATE=5
      - MM_INTEREST_RATE=0.9
      - BANK_NAME=The Bank
      - BANK_STREET=301 Sparkman Drive NW
      - BANK_CITY=Huntsville
      - BANK_STATE=AL
      - BANK_COUNTRY=United States of America
      - BANK_ZIP=35805
      - BANK_PHONE=256-867-5309
      - BANK_TIN=832-23-0684
      - BANK_STATE_ID_NO=531-232-5069
  bmu-frontend:
    restart: always
    build:
      args:
        - REACT_APP_API_URL="test"
      context: "./frontend"
      dockerfile: "./Dockerfile"
  bmu-main:
    restart: always
    build:
      context: "./nginx"
      dockerfile: "./Dockerfile"
    ports:
      - "80:80"
