version: '3.9'

services:
  #bmu-database-dev:
  #  restart: always
  #  build:
  #    context: "./database"
  #    dockerfile: "./Dockerfile"
  #  networks:
  #    - dev-network
  #  ports: 
  #    - "5432:5432"
  bmu-api-dev:
    restart: always
    build:
      context: "./api"
      dockerfile: "./Dockerfile"
    networks:
      - dev-network
    environment:
      - ROUTING_NUMBER=456546102
      - DIVIDEND_RATE=0.15
      - CC_INTEREST_RATE=20.0
      - MORTGAGE_INTEREST_RATE=4.0
      - MM_INTEREST_RATE=0.9
  bmu-frontend-dev:
    restart: always
    build:
      context: "./frontend"
      dockerfile: "./DockerfileDev"
    networks:
      - dev-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
  bmu-main-dev:
    restart: always
    build:
      context: "./nginx"
      dockerfile: "./DockerfileDev"
    networks:
      - dev-network
    ports:
      - "80:80"

networks:
  dev-network:
    name: bmu-dev-network
