version: '3.9'

services:
  bmu-database:
    restart: always
    build:
      context: "./database"
      dockerfile: "./Dockerfile"
    ports: 
      - "5432:5432"
  bmu-api:
    restart: always
    build:
      context: "./api"
      dockerfile: "./Dockerfile"
    ports: 
      - "5000:5000"