version: '3.9'

services:
  bmu-database:
    restart: always
    build:
      context: "./database"
      dockerfile: "./Dockerfile"
    ports: 
      - "5432:5432"
  bmu-frontend-production:
    restart: always
    build:
      args:
        - REACT_APP_API_URL="test"
      context: "./frontend"
      dockerfile: "./Dockerfile"
      args:
        - REACT_APP_API_URL="test"
    ports: 
      - "8008:3000"
  bmu-frontend:
    restart: always
    build:
<<<<<<< Updated upstream
      context: "./frontend"
      dockerfile: "./Dockerfile.dev"
      args:
        - REACT_APP_API_URL="test"
    ports:
      - "8008:3000"
    volumes:
      - "./frontend:/app"
      - '/app/node_modules'
=======
      context: "./nginx"
      dockerfile: "./Dockerfile"
    ports: 
      - "80:80"

volumes:
  frontend:
      
>>>>>>> Stashed changes
