export const USStates = [
    { key: "Alabama", text: "AL", value: "Alabama" },
    { key: "Alaska", text: "AK", value: "Alaska" },
    { key: "Arizona", text: "AZ", value: "Arizona" },
    { key: "Arkansas", text: "AR", value: "Arkansas" },
    { key: "California", text: "CA", value: "California" },
    { key: "Colorado", text: "CO", value: "Colorado" },
    { key: "Connecticut", text: "CT", value: "Connecticut" },
    { key: "Delaware", text: "DE", value: "Delaware" },
    { key: "Florida", text: "FL", value: "Florida" },
    { key: "Georgia", text: "GA", value: "Georgia" },
    { key: "Hawaii", text: "HI", value: "Hawaii" },
    { key: "Idaho", text: "ID", value: "Idaho" },
    { key: "Illinois", text: "IL", value: "Illinois" },
    { key: "Indiana", text: "IN", value: "Indiana" },
    { key: "Iowa", text: "IA", value: "Iowa" },
    { key: "Kansas", text: "KS", value: "Kansas" },
    { key: "Kentucky", text: "KY", value: "Kentucky" },
    { key: "Louisiana", text: "LA", value: "Louisiana" },
    { key: "Maine", text: "ME", value: "Maine" },
    { key: "Maryland", text: "MD", value: "Maryland" },
    { key: "Massachusetts", text: "MA", value: "Massachusetts" },
    { key: "Michigan", text: "MI", value: "Michigan" },
    { key: "Minnesota", text: "MN", value: "Minnesota" },
    { key: "Mississippi", text: "MS", value: "Mississippi" },
    { key: "Missouri", text: "MO", value: "Missouri" },
    { key: "Montana", text: "MT", value: "Montana" },
    { key: "Nebraska", text: "NE", value: "Nebraska" },
    { key: "Nevada", text: "NV", value: "Nevada" },
    { key: "New Hampshire", text: "NH", value: "New Hampshire" },
    { key: "New Jersey", text: "NJ", value: "New Jersey" },
    { key: "New Mexico", text: "NM", value: "New Mexico" },
    { key: "New York", text: "NY", value: "New York" },
    { key: "North Carolina", text: "NC", value: "North Carolina" },
    { key: "North Dakota", text: "ND", value: "North Dakota" },
    { key: "Ohio", text: "OH", value: "Ohio" },
    { key: "Oklahoma", text: "OK", value: "Oklahoma" },
    { key: "Oregon", text: "OR", value: "Oregon" },
    { key: "Pennsylvania", text: "PA", value: "Pennsylvania" },
    { key: "Rhode Island", text: "RI", value: "Rhode Island" },
    { key: "South Carolina", text: "SC", value: "South Carolina" },
    { key: "South Dakota", text: "SD", value: "South Dakota" },
    { key: "Tennessee", text: "TN", value: "Tennessee" },
    { key: "Texas", text: "TX", value: "Texas" },
    { key: "Utah", text: "UT", value: "Utah" },
    { key: "Vermont", text: "VT", value: "Vermont" },
    { key: "Virginia", text: "VA", value: "Virginia" },
    { key: "Washington", text: "WA", value: "Washington" },
    { key: "West Virginia", text: "WV", value: "West Virginia" },
    { key: "Wisconsin", text: "WI", value: "Wisconsin" },
    { key: "Wyoming", text: "WY", value: "Wyoming" },
]